version: '3'
services:
    nodejs_server:
      build:
        context: ./server
      container_name: nodejsserver
      hostname: nodejsserver
      ports:
        - "3000:3000"
      networks:
        - mde
      depends_on:
        - mongo
    
    reactjs_frontend:
      build:
        context: ./frontend
      container_name: reactjsfrontend
      hostname: reactjsfrontend
      ports:
        - "5000:3000"
      networks:
        - mde
      depends_on:
        - nodejs_server

    mongo:
      image: mongo
      container_name: mongo
      volumes:
        - ./mongo:/data/db
      ports:
        - "27017:27017"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
      networks:
        - mde
    mongo-express:
      image: mongo-express
      container_name: mongo-express
      ports:
        - "8081:8081"
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
        - ME_CONFIG_MONGODB_SERVER=mongo
      networks:
        - mde
      depends_on:
        - mongo
    
    nginx:
      build:
        context: ./nginx
      container_name: nginx
      hostname: nginx
      ports:
        - "80:80"
      networks:
        - mde
      depends_on:
        - nodejs_server
networks:
  mde:
    external: true